import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {createClient} from '@supabase/supabase-js'
import {LayoutDashboard,KanbanSquare,List,Plus,LogOut,Search,Printer,Trash2,X,ChevronRight,RefreshCw,Users,Bell,Check,MessageSquare,Paperclip,Upload,Download,History,Filter,Copy,ClipboardList,CheckCircle2,PauseCircle} from 'lucide-react'
import './styles.css'

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)
const STATUSES=['Pendente','Em andamento','Alteração pendente','Publicada','Finalizada','Cancelada']
const OBJECTIVES_BY_PLATFORM={
 'Meta Ads':['Reconhecimento','Alcance','Tráfego','Engajamento','Leads','Promoção do app','Vendas','Remarketing'],
 'Google Ads':['Pesquisa (Search)','Display','Performance Max','Demand Gen','Shopping','Aplicativos','Remarketing'],
 'YouTube Ads':['Alcance em vídeo','Visualizações de vídeo','Conversões em vídeo','Remarketing'],
 'TikTok Ads':['Reconhecimento','Alcance','Tráfego','Visualizações de vídeo','Leads','Conversões','Promoção do app'],
 'LinkedIn Ads':['Reconhecimento','Visitas ao site','Engajamento','Geração de leads','Conversões'],
 'Spotify Ads':['Áudio','Vídeo','Display','Podcast'],
 'Mídia programática':['Display','Vídeo','CTV','Native','DOOH','Remarketing'],
 'Waze Ads':['Pin','Search','Takeover'],
 'Pinterest Ads':['Reconhecimento','Consideração','Conversões'],
 'Outros':['Reconhecimento','Tráfego','Engajamento','Leads','Vendas','Outro']
}
const REQUEST_TYPES=['Publicar nova campanha','Adicionar oferta','Pausar oferta','Reativar oferta','Encerrar oferta','Cancelar oferta','Alterar orçamento','Alterar público','Alterar localização','Alterar período','Alterar CTA ou URL','Duplicar campanha','Pausar plataforma','Reativar plataforma','Finalizar plataforma','Cancelar plataforma','Outro']
const NEXT_ACTIONS=['Aguardando briefing','Aguardando criativo','Aguardando aprovação','Aguardando boleto','Aguardando configuração','Aguardando publicação','Em validação','Sem pendência']
const PLATFORMS=['Meta Ads','Google Ads','YouTube Ads','TikTok Ads','LinkedIn Ads','Spotify Ads','Mídia programática','Waze Ads','Pinterest Ads','Outros']
const PRIORITIES=['Baixa','Normal','Alta','Urgente']
const roleNames={admin:'Administrador',traffic_manager:'Gestor de tráfego',service:'Atendimento'}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—'
const dateTime=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—'

function Login(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [forgot,setForgot]=useState(false)
 async function submit(e){e.preventDefault();setLoading(true);setError('');setMessage('');const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)setError('E-mail ou senha inválidos.');setLoading(false)}
 async function sendReset(e){e.preventDefault();setLoading(true);setError('');setMessage('');const redirectTo=`${window.location.origin}/`;const {error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo});if(error)setError('Não foi possível enviar o link. Confira o e-mail e tente novamente.');else setMessage('Link enviado! Confira sua caixa de entrada e também o spam.');setLoading(false)}
 return <div className="login"><div className="login-card"><img className="login-logo" src="/marca_hip.png" alt="HIP"/><h1>HIP Ads Flow</h1><p>Gestão interna de solicitações de mídias digitais</p>{forgot?<form onSubmit={sendReset}><div className="auth-intro"><strong>Redefinir senha</strong><span>Informe seu e-mail para receber o link de recuperação.</span></div><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@hipweb.com.br" required autoFocus/>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="primary" disabled={loading}>{loading?'Enviando...':'Enviar link de recuperação'}</button><button type="button" className="link-button" onClick={()=>{setForgot(false);setError('');setMessage('')}}>Voltar para o login</button></form>:<form onSubmit={submit}><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@hipweb.com.br" required/><div className="password-label"><label>Senha</label><button type="button" onClick={()=>{setForgot(true);setError('');setMessage('')}}>Esqueci minha senha</button></div><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form>}<small className="version">v1.3.4</small></div></div>
}

function ResetPassword({done}){
 const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false)
 async function submit(e){e.preventDefault();setError('');setMessage('');if(password.length<8){setError('A senha deve ter pelo menos 8 caracteres.');return}if(password!==confirmPassword){setError('As senhas não coincidem.');return}setLoading(true);const {error}=await supabase.auth.updateUser({password});setLoading(false);if(error)setError('Não foi possível alterar a senha. Solicite um novo link e tente novamente.');else{setMessage('Senha atualizada com sucesso.');setTimeout(done,900)}}
 return <div className="login"><div className="login-card"><img className="login-logo" src="/marca_hip.png" alt="HIP"/><h1>Nova senha</h1><p>Cadastre uma nova senha para acessar o HIP Ads Flow.</p><form onSubmit={submit}><label>Nova senha</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required autoFocus/><label>Confirmar nova senha</label><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength="8" required/>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="primary" disabled={loading}>{loading?'Atualizando...':'Salvar nova senha'}</button></form><small className="version">v1.3.4</small></div></div>
}

function App(){
 const [session,setSession]=useState(null); const [passwordRecovery,setPasswordRecovery]=useState(false); const [profile,setProfile]=useState(null); const [requests,setRequests]=useState([]); const [clients,setClients]=useState([]); const [notifications,setNotifications]=useState([]); const [notes,setNotes]=useState([]); const [attachments,setAttachments]=useState([]); const [history,setHistory]=useState([]); const [operations,setOperations]=useState([]); const [view,setView]=useState('dashboard'); const [loading,setLoading]=useState(true); const [toast,setToast]=useState(''); const [duplicateData,setDuplicateData]=useState(null); const [modal,setModal]=useState(false); const [selected,setSelected]=useState(null); const [bellOpen,setBellOpen]=useState(false); const [filters,setFilters]=useState({query:'',client:'',status:'',platform:'',priority:'',start:'',end:''})
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setPasswordRecovery(true)});return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session){bootstrap()}else{setProfile(null);setLoading(false)}},[session])
 useEffect(()=>{if(!session)return;const timer=setInterval(()=>{loadRequests(false);loadNotifications()},30000);return()=>clearInterval(timer)},[session])
 async function bootstrap(){setLoading(true);await supabase.rpc('finalize_expired_requests');await Promise.all([loadProfile(),loadRequests(false),loadClients(),loadNotifications()]);setLoading(false)}
 async function loadProfile(){const {data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error)alert('Perfil não encontrado. Confirme o cadastro na tabela profiles.');setProfile(data)}
 async function loadRequests(show=true){if(show)setLoading(true);await supabase.rpc('finalize_expired_requests');const {data,error}=await supabase.from('ad_requests_with_creator').select('*').order('created_at',{ascending:false});if(error)alert(error.message);setRequests(data||[]);if(selected){const fresh=(data||[]).find(r=>r.id===selected.id);if(fresh)setSelected(fresh)}if(show)setLoading(false)}
 async function loadClients(){const {data,error}=await supabase.from('clients').select('*').order('name');if(error)alert(error.message);setClients(data||[])}
 async function loadNotifications(){const {data}=await supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(30);setNotifications(data||[])}
 async function loadNotes(requestId){const {data,error}=await supabase.from('request_notes_with_author').select('*').eq('request_id',requestId).order('created_at',{ascending:true});if(error)alert(error.message);setNotes(data||[])}
 async function loadAttachments(requestId){const {data,error}=await supabase.from('request_attachments_with_author').select('*').eq('request_id',requestId).order('created_at',{ascending:false});if(error)alert(error.message);setAttachments(data||[])}
 async function loadHistory(requestId){const {data,error}=await supabase.from('request_history_with_actor').select('*').eq('request_id',requestId).order('created_at',{ascending:false});if(error)alert(error.message);setHistory(data||[])}
 async function loadOperations(requestId){const {data,error}=await supabase.from('request_operations_with_people').select('*').eq('request_id',requestId).order('created_at',{ascending:false});if(error)alert(error.message);setOperations(data||[])}
 async function openDetails(r){setSelected(r);await Promise.all([loadNotes(r.id),loadAttachments(r.id),loadHistory(r.id),loadOperations(r.id)])}
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast])
 const filtered=useMemo(()=>requests.filter(r=>{
  const q=filters.query.trim().toLowerCase()
  return (!q||[r.code,r.client,r.campaign,r.platform,r.status,r.requester_name,r.objective].join(' ').toLowerCase().includes(q))
   &&(!filters.client||r.client===filters.client)&&(!filters.status||r.status===filters.status)
   &&(!filters.platform||r.platform===filters.platform)&&(!filters.priority||r.priority===filters.priority)
   &&(!filters.start||r.start_date>=filters.start)&&(!filters.end||r.end_date<=filters.end)
   &&(!filters.period||matchesPeriod(r,filters.period))
 }),[requests,filters])
 if(passwordRecovery)return <ResetPassword done={()=>{setPasswordRecovery(false);window.history.replaceState({},document.title,window.location.pathname)}}/>
 if(!session)return <Login/>
 if(!profile)return <div className="center">Carregando seu perfil...</div>
 const canUpdate=['admin','traffic_manager'].includes(profile.role), canDelete=profile.role==='admin', unread=notifications.filter(n=>!n.read_at).length
 async function changeStatus(id,status){const {error}=await supabase.from('ad_requests').update({status,updated_by:session.user.id}).eq('id',id);if(error)alert(error.message);else{setToast('Status atualizado com sucesso.');await loadRequests(false);await loadNotifications()}}
 async function remove(id){if(!confirm('Excluir esta solicitação definitivamente?'))return;const {error}=await supabase.from('ad_requests').delete().eq('id',id);if(error)alert(error.message);else{setToast('Solicitação removida.');setSelected(null);loadRequests(false)}}
 async function markAllRead(){await supabase.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);loadNotifications()}
 return <div className="app"><aside><div className="logo"><img src="/marca_hip.png" alt="HIP Ads Flow"/></div><nav><Nav active={view==='dashboard'} onClick={()=>setView('dashboard')} icon={<LayoutDashboard/>}>Dashboard</Nav><Nav active={view==='kanban'} onClick={()=>setView('kanban')} icon={<KanbanSquare/>}>Kanban</Nav><Nav active={view==='list'} onClick={()=>setView('list')} icon={<List/>}>Solicitações</Nav><Nav active={view==='clients'} onClick={()=>setView('clients')} icon={<Users/>}>Clientes</Nav></nav><div className="user"><strong>{profile.full_name}</strong><span>{roleNames[profile.role]}</span><small>HIP Ads Flow v1.3.4</small><button onClick={()=>supabase.auth.signOut()}><LogOut/> Sair</button></div></aside><main><header><div><h1>{view==='dashboard'?'Visão geral':view==='kanban'?'Kanban':view==='clients'?'Clientes':'Solicitações'}</h1><p>HIP Ads Flow</p></div><div className="header-actions"><div className="bell-wrap"><button className="ghost bell" onClick={()=>setBellOpen(!bellOpen)}><Bell/>{unread>0&&<span>{unread}</span>}</button>{bellOpen&&<NotificationPanel items={notifications} markAllRead={markAllRead}/>}</div><button className="ghost" onClick={()=>{loadRequests();loadNotifications()}}><RefreshCw/></button>{view!=='clients'&&<button className="primary" onClick={()=>setModal(true)}><Plus/> Nova solicitação</button>}</div></header>{['kanban','list'].includes(view)&&<AdvancedFilters filters={filters} setFilters={setFilters} clients={clients} count={filtered.length}/>}{loading?<div className="center">Carregando...</div>:view==='dashboard'?<Dashboard data={requests} open={openDetails}/>:view==='kanban'?<Kanban data={filtered} open={openDetails} canUpdate={canUpdate} changeStatus={changeStatus}/>:view==='clients'?<Clients data={clients} canManage={canDelete} reload={loadClients}/>:<Table data={filtered} open={openDetails}/>}</main>{modal&&<RequestForm userId={session.user.id} clients={clients} requests={requests} initialData={duplicateData} close={()=>{setModal(false);setDuplicateData(null)}} saved={()=>{setToast(duplicateData?'Solicitação duplicada com sucesso.':'Solicitação criada com sucesso.');setModal(false);setDuplicateData(null);loadRequests(false);loadNotifications()}}/>}{selected&&<Details r={selected} notes={notes} attachments={attachments} history={history} operations={operations} setOperations={setOperations} setAttachments={setAttachments} setHistory={setHistory} reloadNotes={()=>loadNotes(selected.id)} userId={session.user.id} close={()=>setSelected(null)} canUpdate={canUpdate} canDelete={canDelete} changeStatus={changeStatus} remove={remove} duplicate={()=>{setDuplicateData(selected);setSelected(null);setModal(true)}}/>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}
function Nav({active,onClick,icon,children}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{children}</span></button>}
function Dashboard({data,open}){
 const today=new Date().toISOString().slice(0,10);const n=new Date();n.setDate(n.getDate()+7);const next=n.toISOString().slice(0,10)
 const month=today.slice(0,7)
 const active=data.filter(r=>!['Finalizada','Cancelada'].includes(r.status))
 const finalizedMonth=data.filter(r=>r.status==='Finalizada'&&String(r.updated_at||r.end_date||'').slice(0,7)===month)
 const soon=data.filter(r=>!['Finalizada','Cancelada'].includes(r.status)&&r.end_date>=today&&r.end_date<=next).sort((a,b)=>a.end_date.localeCompare(b.end_date))
 const byClient=Object.entries(data.reduce((a,r)=>{a[r.client]=(a[r.client]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,6)
 const max=byClient[0]?.[1]||1
 return <><section className="metrics dashboard-metrics"><Metric label="Solicitações ativas" value={active.length}/><Metric label="Pendentes" value={data.filter(r=>r.status==='Pendente').length}/><Metric label="Em andamento" value={data.filter(r=>r.status==='Em andamento').length}/><Metric label="Alterações pendentes" value={data.filter(r=>r.status==='Alteração pendente').length}/><Metric label="Publicadas" value={data.filter(r=>r.status==='Publicada').length}/><Metric label="Finalizadas no mês" value={finalizedMonth.length}/></section>
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Solicitações recentes</h2><p>Últimas demandas registradas</p></div></div><Table data={data.slice(0,7)} open={open}/></section>
 <section className="panel"><div className="panel-head"><div><h2>Demandas por cliente</h2><p>Volume total de solicitações</p></div></div><div className="client-bars">{byClient.map(([name,v])=><div key={name}><div><strong>{name}</strong><span>{v}</span></div><div className="bar"><i style={{width:`${v/max*100}%`}}/></div></div>)}{!byClient.length&&<p className="empty-note">Sem dados ainda.</p>}</div></section></div>
 <section className="panel"><div className="panel-head"><div><h2>Próximos vencimentos</h2><p>Encerramento nos próximos sete dias</p></div></div><Table data={soon.slice(0,8)} open={open}/></section></>
}
function Metric({label,value,compact}){return <div className="metric"><span>{label}</span><strong className={compact?'compact':''}>{value}</strong></div>}
function Status({value}){return <span className={'status s-'+value.toLowerCase().replaceAll(' ','-')}>{value}</span>}
function Table({data,open}){const [sort,setSort]=useState({key:'created_at',dir:'desc'});const sorted=useMemo(()=>[...data].sort((a,b)=>{const av=String(a[sort.key]||'').toLowerCase(),bv=String(b[sort.key]||'').toLowerCase();return(av>bv?1:av<bv?-1:0)*(sort.dir==='asc'?1:-1)}),[data,sort]);const toggle=key=>setSort(s=>({key,dir:s.key===key&&s.dir==='asc'?'desc':'asc'}));return <div className="table-wrap"><table><thead><tr><th onClick={()=>toggle('code')}>Código</th><th onClick={()=>toggle('client')}>Cliente</th><th onClick={()=>toggle('campaign')}>Campanha</th><th onClick={()=>toggle('platform')}>Plataforma</th><th onClick={()=>toggle('end_date')}>Fim</th><th onClick={()=>toggle('status')}>Status</th><th></th></tr></thead><tbody>{sorted.length?sorted.map(r=><tr key={r.id} onClick={()=>open(r)}><td><b>{r.code}</b></td><td>{r.client}</td><td>{r.campaign}</td><td>{r.platform}</td><td>{date(r.end_date)}</td><td><Status value={r.status}/></td><td><ChevronRight/></td></tr>):<tr><td colSpan="7" className="empty">Nenhuma solicitação encontrada.</td></tr>}</tbody></table></div>}
function matchesPeriod(r,period){const today=new Date();today.setHours(0,0,0,0);const d=new Date((r.start_date||r.created_at||'')+'T12:00:00');if(period==='today')return d.toDateString()===today.toDateString();if(period==='week'){const end=new Date(today);end.setDate(today.getDate()+7);return d>=today&&d<=end}if(period==='month')return d.getMonth()===today.getMonth()&&d.getFullYear()===today.getFullYear();return true}
function AdvancedFilters({filters,setFilters,clients,count}){const [open,setOpen]=useState(false);const set=(k,v)=>setFilters({...filters,[k]:v});const active=Object.values(filters).filter(Boolean).length;const reset=()=>setFilters({query:'',client:'',status:'',platform:'',priority:'',start:'',end:'',period:''});return <section className="filter-box"><div className="quick-filters"><div>{['','Pendente','Em andamento','Alteração pendente','Publicada','Finalizada','Cancelada'].map(v=><button key={v||'Todos'} className={filters.status===v?'active':''} onClick={()=>set('status',v)}>{v||'Todos'}</button>)}</div><div>{[['','Todos os períodos'],['today','Hoje'],['week','Esta semana'],['month','Este mês']].map(([v,l])=><button key={l} className={filters.period===v?'active':''} onClick={()=>set('period',v)}>{l}</button>)}</div></div><div className="filter-main"><Search/><input value={filters.query} onChange={e=>set('query',e.target.value)} placeholder="Pesquisar cliente, campanha, plataforma, objetivo ou solicitante..."/><button className={active?'filter-toggle active':'filter-toggle'} onClick={()=>setOpen(!open)}><Filter/> Filtros {active>0&&<span>{active}</span>}</button><strong>{count} resultado(s)</strong></div>{open&&<div className="filter-grid"><Select label="Cliente" value={filters.client} set={v=>set('client',v)} options={['',...clients.map(c=>c.name)]}/><Select label="Status" value={filters.status} set={v=>set('status',v)} options={['',...STATUSES]}/><Select label="Plataforma" value={filters.platform} set={v=>set('platform',v)} options={['',...PLATFORMS]}/><Select label="Prioridade" value={filters.priority} set={v=>set('priority',v)} options={['',...PRIORITIES]}/><Field label="Início a partir de" type="date" value={filters.start} set={v=>set('start',v)}/><Field label="Final até" type="date" value={filters.end} set={v=>set('end',v)}/><button className="secondary clear-filter" onClick={reset}>Limpar filtros</button></div>}</section>}
function Kanban({data,open,canUpdate,changeStatus}){return <div className="kanban">{STATUSES.map(s=><section className="column" key={s}><div className="column-head"><h3>{s}</h3><span>{data.filter(r=>r.status===s).length}</span></div>{data.filter(r=>r.status===s).map(r=><article className="card" key={r.id} onClick={()=>open(r)}><small>{r.code}</small><h4>{r.client}</h4><p>{r.campaign}</p><div><span>{r.platform}</span><b>{money(r.budget)}</b></div>{canUpdate&&<select value={r.status} onClick={e=>e.stopPropagation()} onChange={e=>changeStatus(r.id,e.target.value)}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select>}</article>)}</section>)}</div>}
function Clients({data,canManage,reload}){const [name,setName]=useState('');const [query,setQuery]=useState('');const [saving,setSaving]=useState(false);const visible=data.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));async function add(e){e.preventDefault();const clean=name.trim().replace(/\s+/g,' ');if(!clean)return;if(data.some(c=>c.name.localeCompare(clean,'pt-BR',{sensitivity:'base'})===0)){alert('Este cliente já está cadastrado.');return}setSaving(true);const {error}=await supabase.from('clients').insert({name:clean,is_active:true});setSaving(false);if(error)alert(error.message);else{setName('');reload()}}async function toggle(c){const {error}=await supabase.from('clients').update({is_active:!c.is_active}).eq('id',c.id);if(error)alert(error.message);else reload()}return <section className="panel clients-panel"><div className="panel-head"><h2>Cadastro de clientes</h2><p>Pesquise, cadastre e controle clientes ativos e inativos.</p></div>{canManage&&<form className="client-form" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do cliente"/><button className="primary" disabled={saving}><Plus/> Cadastrar</button></form>}<div className="client-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar cliente..."/></div><div className="client-list">{visible.map(c=><div key={c.id}><div><strong>{c.name}</strong><span className={c.is_active?'client-state active':'client-state'}>{c.is_active?'Ativo':'Inativo'}</span></div>{canManage&&<button className="secondary client-toggle" onClick={()=>toggle(c)}>{c.is_active?'Inativar':'Ativar'}</button>}</div>)}{!visible.length&&<p className="empty">Nenhum cliente encontrado.</p>}</div></section>}
function RequestForm({userId,clients,requests,initialData,close,saved}){
 const defaultPlatform=initialData?.platform||'Meta Ads'
 const blank={client:'',requester_name:'',campaign:'',request_type:'Publicar nova campanha',affected_item:'',objective:OBJECTIVES_BY_PLATFORM[defaultPlatform][0],platform:defaultPlatform,budget_type:'Total',budget:'',start_date:'',end_date:'',priority:'Normal',audience:'',location:'Uberlândia - MG',destination_url:'',cta:'',next_action:'Aguardando briefing',assigned_to_name:'Henrique',notes:''}
 const duplicated=initialData?{...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,initialData[k]??blank[k]])),campaign:`${initialData.campaign} - cópia`,request_type:'Duplicar campanha',start_date:'',end_date:'',priority:'Normal'}:blank
 const [saving,setSaving]=useState(false)
 const [mode,setMode]=useState(initialData?'new':'existing')
 const [projectKey,setProjectKey]=useState('')
 const [f,setF]=useState(duplicated)
 const set=(k,v)=>setF(x=>({...x,[k]:v}))
 function setPlatform(v){setF(x=>({...x,platform:v,objective:OBJECTIVES_BY_PLATFORM[v][0]}))}
 const projects=useMemo(()=>{
  const map=new Map()
  ;(requests||[]).forEach(r=>{
   if(!r.client||!r.campaign)return
   const key=[r.client,r.campaign,r.platform||''].join('|||')
   if(!map.has(key)||new Date(r.created_at)>new Date(map.get(key).created_at))map.set(key,r)
  })
  return [...map.entries()].map(([key,r])=>({key,r,label:`${r.client} — ${r.campaign}${r.platform?` • ${r.platform}`:''}`})).sort((a,b)=>a.label.localeCompare(b.label,'pt-BR'))
 },[requests])
 function chooseProject(key){
  setProjectKey(key)
  const selected=projects.find(p=>p.key===key)?.r
  if(!selected)return
  setF(x=>({...x,
   client:selected.client||'',campaign:selected.campaign||'',platform:selected.platform||'Meta Ads',objective:selected.objective||OBJECTIVES_BY_PLATFORM[selected.platform||'Meta Ads'][0],budget_type:selected.budget_type||'Total',budget:selected.budget??'',start_date:selected.start_date||'',end_date:selected.end_date||'',audience:selected.audience||'',location:selected.location||'',destination_url:selected.destination_url||'',cta:selected.cta||'',assigned_to_name:selected.assigned_to_name||'Henrique',request_type:'Adicionar oferta',affected_item:'',notes:'',priority:'Normal',next_action:'Aguardando briefing'}))
 }
 function changeMode(value){
  setMode(value);setProjectKey('')
  if(value==='new')setF(blank)
  else setF({...blank,request_type:'Adicionar oferta'})
 }
 async function submit(e){
  e.preventDefault()
  if(mode==='existing'&&!projectKey){alert('Selecione a campanha/projeto em que a solicitação será criada.');return}
  setSaving(true)
  const {error}=await supabase.from('ad_requests').insert({...f,budget:Number(f.budget||0),status:'Pendente',created_by:userId})
  setSaving(false)
  if(error)alert(error.message);else saved()
 }
 const activeClients=clients.filter(c=>c.is_active!==false)
 const isExisting=mode==='existing'&&!initialData
 return <div className="overlay"><div className="modal form-modal large-modal"><div className="modal-head"><div><h2>{initialData?'Duplicar solicitação':'Nova solicitação'}</h2><p>{initialData?'Revise os dados antes de salvar.':'Crie a demanda diretamente dentro de uma campanha existente.'}</p></div><button onClick={close}><X/></button></div><form onSubmit={submit} className="request-form">
 {!initialData&&<div className="request-mode"><button type="button" className={mode==='existing'?'active':''} onClick={()=>changeMode('existing')}><ClipboardList/> Solicitação em campanha existente</button><button type="button" className={mode==='new'?'active':''} onClick={()=>changeMode('new')}><Plus/> Nova campanha</button></div>}
 {isExisting&&<FormSection title="Escolha o projeto"><label className="span">Campanha / projeto<select value={projectKey} onChange={e=>chooseProject(e.target.value)} required><option value="">Selecione uma campanha...</option>{projects.map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label>{projectKey&&<div className="project-summary span"><span><strong>Cliente:</strong> {f.client}</span><span><strong>Campanha:</strong> {f.campaign}</span><span><strong>Plataforma:</strong> {f.platform}</span><span><strong>Objetivo:</strong> {f.objective}</span></div>}</FormSection>}
 {(!isExisting||projectKey)&&<>
 <FormSection title="Solicitação"><Select label="Tipo da solicitação" value={f.request_type} set={v=>set('request_type',v)} options={isExisting?REQUEST_TYPES.filter(x=>x!=='Publicar nova campanha'):REQUEST_TYPES} required/><Field label="Oferta ou item afetado" value={f.affected_item} set={v=>set('affected_item',v)}/><Field label="Solicitante" value={f.requester_name} set={v=>set('requester_name',v)} required/><Select label="Prioridade" value={f.priority} set={v=>set('priority',v)} options={PRIORITIES}/><Select label="Próxima ação" value={f.next_action} set={v=>set('next_action',v)} options={NEXT_ACTIONS}/><Field label="Responsável operacional" value={f.assigned_to_name} set={v=>set('assigned_to_name',v)}/><label className="span">Descrição da solicitação<textarea value={f.notes} onChange={e=>set('notes',e.target.value)} rows="4" placeholder="Descreva com clareza o que precisa ser executado." required/></label></FormSection>
 {!isExisting&&<><FormSection title="Campanha e plataforma"><Select label="Cliente" value={f.client} set={v=>set('client',v)} options={['',...activeClients.map(c=>c.name)]} required/><Field label="Nome da campanha / período" value={f.campaign} set={v=>set('campaign',v)} required/><Select label="Plataforma" value={f.platform} set={setPlatform} options={PLATFORMS}/><Select label="Objetivo / tipo de campanha" value={f.objective} set={v=>set('objective',v)} options={OBJECTIVES_BY_PLATFORM[f.platform]} required/></FormSection><FormSection title="Período e investimento"><Field label="Data inicial" type="date" value={f.start_date} set={v=>set('start_date',v)} required/><Field label="Data final" type="date" value={f.end_date} set={v=>set('end_date',v)} required/><Field label="Investimento (R$)" type="number" value={f.budget} set={v=>set('budget',v)} required/><Select label="Tipo de verba" value={f.budget_type} set={v=>set('budget_type',v)} options={['Total','Diária','Mensal']}/></FormSection><FormSection title="Segmentação e destino"><Field label="Público" value={f.audience} set={v=>set('audience',v)} span/><Field label="Localização" value={f.location} set={v=>set('location',v)} span/><Field label="URL de destino" type="url" value={f.destination_url} set={v=>set('destination_url',v)} span/><Field label="CTA" value={f.cta} set={v=>set('cta',v)} span/></FormSection></>}
 </>}
 <div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving||isExisting&&!projectKey}>{saving?'Salvando...':initialData?'Duplicar solicitação':isExisting?'Criar solicitação na campanha':'Criar campanha'}</button></div></form></div></div>
}
function FormSection({title,children}){return <section className="form-section"><h3>{title}</h3><div className="form-grid">{children}</div></section>}
function Field({label,value,set,type='text',required,span}){return <label className={span?'span':''}>{label}<input type={type} value={value} onChange={e=>set(e.target.value)} required={required}/></label>}
function Select({label,value,set,options,required}){return <label>{label}<select value={value} onChange={e=>set(e.target.value)} required={required}>{options.map(o=><option key={o} value={o}>{o||'Selecione...'}</option>)}</select></label>}
function Details({r,notes,attachments,history,operations,setOperations,setAttachments,setHistory,reloadNotes,userId,close,canUpdate,canDelete,changeStatus,remove,duplicate}){
 const [text,setText]=useState('');const [saving,setSaving]=useState(false);const [opType,setOpType]=useState('Adicionar oferta');const [opItem,setOpItem]=useState('');const [opRequester,setOpRequester]=useState('');const [opNote,setOpNote]=useState('');const [uploading,setUploading]=useState(false);const [tab,setTab]=useState('details');const locked=['Finalizada','Cancelada'].includes(r.status)
 function print(){window.print()}
 async function addNote(e){e.preventDefault();if(!text.trim()||locked)return;setSaving(true);const {error}=await supabase.from('request_notes').insert({request_id:r.id,note:text.trim(),created_by:userId});setSaving(false);if(error)alert(error.message);else{setText('');await reloadNotes()}}
 async function addOperation(e){e.preventDefault();if(!opRequester.trim()||!opNote.trim())return;setSaving(true);const {error}=await supabase.from('request_operations').insert({request_id:r.id,operation_type:opType,affected_item:opItem.trim(),requester_name:opRequester.trim(),request_note:opNote.trim(),created_by:userId});setSaving(false);if(error)alert(error.message);else{setOpItem('');setOpNote('');const {data}=await supabase.from('request_operations_with_people').select('*').eq('request_id',r.id).order('created_at',{ascending:false});setOperations(data||[]);await changeStatus(r.id,'Alteração pendente')}}
 async function completeOperation(op){const note=prompt('Observação de conclusão (obrigatória):');if(!note?.trim())return;const {error}=await supabase.from('request_operations').update({status:'Concluída',completion_note:note.trim(),completed_by:userId,completed_at:new Date().toISOString()}).eq('id',op.id);if(error)alert(error.message);else{const {data}=await supabase.from('request_operations_with_people').select('*').eq('request_id',r.id).order('created_at',{ascending:false});setOperations(data||[]);if((data||[]).every(x=>x.status==='Concluída'))await changeStatus(r.id,'Publicada')}}

 async function uploadFile(e){const file=e.target.files?.[0];e.target.value='';if(!file||locked)return;if(file.size>25*1024*1024){alert('O arquivo deve ter no máximo 25 MB.');return}setUploading(true);const clean=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${r.id}/${Date.now()}-${clean}`;const {error:up}=await supabase.storage.from('request-files').upload(path,file);if(up){alert(up.message);setUploading(false);return}const {error}=await supabase.from('request_attachments').insert({request_id:r.id,file_name:file.name,file_path:path,file_type:file.type||'application/octet-stream',file_size:file.size,created_by:userId});if(error){await supabase.storage.from('request-files').remove([path]);alert(error.message)}else{const {data}=await supabase.from('request_attachments_with_author').select('*').eq('request_id',r.id).order('created_at',{ascending:false});setAttachments(data||[]);const {data:h}=await supabase.from('request_history_with_actor').select('*').eq('request_id',r.id).order('created_at',{ascending:false});setHistory(h||[])}setUploading(false)}
 async function openFile(a){const {data,error}=await supabase.storage.from('request-files').createSignedUrl(a.file_path,120);if(error)alert(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <div className="overlay"><div className="modal details large-modal"><div className="modal-head"><div><small>{r.code}</small><h2>{r.client}</h2><p>{r.campaign}</p></div><button onClick={close}><X/></button></div>
 <div className="detail-tabs"><button className={tab==='details'?'active':''} onClick={()=>setTab('details')}>Detalhes</button><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><MessageSquare/> Observações <span>{notes.length}</span></button><button className={tab==='files'?'active':''} onClick={()=>setTab('files')}><Paperclip/> Arquivos <span>{attachments.length}</span></button><button className={tab==='operations'?'active':''} onClick={()=>setTab('operations')}><ClipboardList/> Operações <span>{operations.filter(o=>o.status!=='Concluída').length}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History/> Histórico <span>{history.length}</span></button></div>
 {tab==='details'&&<><div className="detail-grid"><Item label="Status"><Status value={r.status}/></Item><Item label="Plataforma">{r.platform}</Item><Item label="Tipo da solicitação">{r.request_type||'Publicar nova campanha'}</Item><Item label="Item afetado">{r.affected_item||'—'}</Item><Item label="Objetivo">{r.objective}</Item><Item label="Investimento">{money(r.budget)} • {r.budget_type}</Item><Item label="Período">{date(r.start_date)} até {date(r.end_date)}</Item><Item label="Prioridade">{r.priority}</Item><Item label="Solicitante">{r.requester_name}</Item><Item label="Responsável">{r.assigned_to_name||'—'}</Item><Item label="Próxima ação">{r.next_action||'—'}</Item><Item label="Criado por">{r.creator_name||'—'}</Item><Item label="Público" span>{r.audience||'—'}</Item><Item label="Localização" span>{r.location||'—'}</Item><Item label="Destino" span>{r.destination_url||'—'}</Item><Item label="CTA" span>{r.cta||'—'}</Item>{r.notes&&<Item label="Observação inicial" span>{r.notes}</Item>}</div>{canUpdate&&<div className="status-edit"><label>Alterar status</label><select value={r.status} onChange={e=>changeStatus(r.id,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>}</>}
 {tab==='notes'&&<section className="notes-section tab-section"><div className="notes-title"><div><MessageSquare/><strong>Observações internas</strong></div>{locked&&<span>Bloqueadas após finalização</span>}</div><div className="notes-list">{notes.map(n=><div className="note" key={n.id}><div><strong>{n.author_name||'Usuário'}</strong><span>{dateTime(n.created_at)}</span></div><p>{n.note}</p></div>)}{!notes.length&&<p className="empty-note">Nenhuma observação registrada.</p>}</div><form className="note-form" onSubmit={addNote}><textarea value={text} onChange={e=>setText(e.target.value)} disabled={locked} placeholder={locked?'Solicitação finalizada: novas observações estão bloqueadas.':'Escreva uma observação...'} rows="3"/><button className="primary" disabled={locked||saving||!text.trim()}>{saving?'Salvando...':'Adicionar observação'}</button></form></section>}
 {tab==='files'&&<section className="tab-section"><div className="section-toolbar"><div><h3>Arquivos da solicitação</h3><p>JPG, PNG, PDF, MP4 e documentos com até 25 MB.</p></div><label className={locked?'upload-button disabled':'upload-button'}><Upload/>{uploading?'Enviando...':'Anexar arquivo'}<input type="file" disabled={locked||uploading} onChange={uploadFile}/></label></div>{locked&&<div className="locked-message">Solicitação finalizada: novos anexos estão bloqueados.</div>}<div className="file-list">{attachments.map(a=><div className="file-row" key={a.id}><div className="file-info"><strong>{a.file_name}</strong><span>{a.author_name||'Usuário'} • {dateTime(a.created_at)} • {(a.file_size/1024/1024).toFixed(2)} MB</span></div><button className="secondary icon-only" onClick={()=>openFile(a)}><Download/></button></div>)}{!attachments.length&&<p className="empty-note">Nenhum arquivo anexado.</p>}</div></section>}

 {tab==='operations'&&<section className="tab-section operations-section"><div className="operations-head"><div><h3>Solicitações de alteração</h3><p>Qualquer nova solicitação em campanha publicada muda o status para Alteração pendente.</p></div></div><div className="operation-list">{operations.map(op=><article className="operation-card" key={op.id}><div className="operation-top"><div><strong>{op.operation_type}</strong><span>{op.affected_item||'Campanha / plataforma'}</span></div><span className={op.status==='Concluída'?'op-status done':'op-status'}>{op.status}</span></div><p>{op.request_note}</p><small>Solicitado por {op.requester_name} • {dateTime(op.created_at)}</small>{op.completion_note&&<div className="completion-note"><strong>Conclusão:</strong> {op.completion_note}<small>{op.completed_by_name||'Usuário'} • {dateTime(op.completed_at)}</small></div>}{canUpdate&&op.status!=='Concluída'&&<button className="primary compact-button" onClick={()=>completeOperation(op)}><CheckCircle2/> Marcar como concluída</button>}</article>)}{!operations.length&&<p className="empty-note">Nenhuma alteração registrada.</p>}</div>{!locked&&<form className="operation-form" onSubmit={addOperation}><h4>Registrar nova alteração</h4><div className="form-grid"><Select label="Tipo" value={opType} set={setOpType} options={REQUEST_TYPES.filter(x=>x!=='Publicar nova campanha')}/><Field label="Oferta ou item afetado" value={opItem} set={setOpItem}/><Field label="Quem solicitou" value={opRequester} set={setOpRequester} required/><label className="span">Observação / motivo<textarea value={opNote} onChange={e=>setOpNote(e.target.value)} rows="3" required/></label></div><button className="primary" disabled={saving}>{saving?'Salvando...':'Registrar alteração'}</button></form>}</section>}
 {tab==='history'&&<section className="tab-section"><h3>Linha do tempo</h3><div className="timeline">{history.map(h=><div className="timeline-item" key={h.id}><i/><div><strong>{h.description}</strong><span>{h.actor_name||'Sistema'} • {dateTime(h.created_at)}</span></div></div>)}{!history.length&&<p className="empty-note">Nenhum evento registrado.</p>}</div></section>}
 <div className="modal-actions"><button className="secondary" onClick={duplicate}><Copy/> Duplicar</button><button className="secondary" onClick={print}><Printer/> Imprimir</button>{canDelete&&<button className="danger" onClick={()=>remove(r.id)}><Trash2/> Excluir</button>}</div></div></div>
}
function Item({label,children,span}){return <div className={span?'item span':'item'}><span>{label}</span><strong>{children}</strong></div>}
function NotificationPanel({items,markAllRead}){return <div className="notification-panel"><div className="notification-head"><strong>Notificações</strong><button onClick={markAllRead}><Check/> Marcar como lidas</button></div><div className="notification-list">{items.map(n=><div className={n.read_at?'notification':'notification unread'} key={n.id}><strong>{n.title}</strong><p>{n.message}</p><span>{dateTime(n.created_at)}</span></div>)}{!items.length&&<p className="empty-note">Nenhuma notificação.</p>}</div></div>}
createRoot(document.getElementById('root')).render(<App/>)
